packages:
  - 'packages/agents-a365-*'
  - 'tests-agent/*'
  - 'tests'

catalog:
  # Claude AI package
  "@anthropic-ai/claude-agent-sdk": "^0.1.30"

  # Azure packages
  "@azure/identity": "^4.12.1"
  "@azure/monitor-opentelemetry-exporter": "^1.0.0-beta.32"
  
  # Express framework
  "express": "^5.2.0"

  # JSON Web Token
  "jsonwebtoken": "^9.0.3"

  # LangChain packages - use latest stable
  "langchain": "^1.2.3"
  "@langchain/core": "^1.1.8"
  "@langchain/mcp-adapters": "^1.1.1"

  # Microsoft 365 Agents SDK packages
  "@microsoft/agents-hosting": "^1.1.0-alpha.85"
  "@microsoft/agents-activity": "^1.1.0-alpha.85"

  # Hono - required peer dependency for MCP SDK and OpenAI agents
  "hono": "^4.11.4"

  # Model Context Protocol SDK
  "@modelcontextprotocol/sdk": "^1.25.2"

  # OpenAI Agents packages
  "@openai/agents": "^0.4.0"
  "@openai/agents-core": "^0.4.0"
  "@openai/agents-openai": "^0.4.0"
  "openai": "^4.8.0"

  # OpenTelemetry packages - align versions
  "@opentelemetry/core": "^2.2.0"
  "@opentelemetry/api": "^1.9.0"
  "@opentelemetry/exporter-trace-otlp-http": "^0.205.0"
  "@opentelemetry/instrumentation": "^0.204.0"
  "@opentelemetry/resources": "^2.1.0"
  "@opentelemetry/sdk-node": "^0.204.0"
  "@opentelemetry/sdk-trace-base": "^2.1.0"
  "@opentelemetry/semantic-conventions": "^1.37.0"

  # Development dependencies - align versions
  "@babel/preset-typescript": "^7.27.1"
  "@eslint/js": "^9.39.1"
  "@jest/globals": "^30.2.0"
  "@microsoft/m365agentsplayground": "^0.2.18"
  "@types/express": "^5.0.0"
  "@types/jest": "^30.0.0"
  "@types/jsonwebtoken": "^9.0.10"
  "@types/node": "^20.17.0"
  "@typescript-eslint/eslint-plugin": "^8.47.0"
  "@typescript-eslint/parser": "^8.47.0"
  "cross-env": "^7.0.3"
  "dotenv": "^17.2.2"
  "eslint": "^9.39.1"
  "jest": "^30.2.0"
  "js-yaml": "^4.1.1"
  "nodemon": "^3.1.10"
  "rimraf": "^6.0.0"
  "ts-jest": "^29.4.5"
  "tsx": "^4.21.0"
  "typescript": "^5.9.3"
  "typescript-eslint": "^8.47.0"

overrides:
  # Zod
  "zod": "^4.1.12"

  # Development dependencies - align versions
  "@types/uuid": "^9.0.0"
  "uuid": "^9.0.0"

# Workspace settings
linkWorkspacePackages: true
sharedWorkspaceLockfile: true
saveWorkspaceProtocol: "rolling"
hoistWorkspacePackages: true

# Node.js version specification
useNodeVersion: "20.18.0"

# Dependency resolution settings
resolutionMode: "highest"
autoInstallPeers: true
strictPeerDependencies: false

# Performance settings
nodeLinker: "hoisted"
enableModulesDir: true
virtualStoreDir: "node_modules/.pnpm"

# Security settings
auditConfig:
  ignoreCves: []
  ignoreGhsas: []